name: Stockfish_Start
on:
  workflow_dispatch:
  push:
    branches:
      - Xmaster
  pull_request:
    branches:
      - Xmaster
jobs:
  ARM_Binaries:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/stockfish_arm_binaries.yml
  ArmBinaries:
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/stockfish_armBinaries.yml
